In [89]:
seed = np.array([[0,0,0], [0,1,0],[0,2,0],[0,3,0], [0,4,0]])
seed_next_possible = np.array([[-1,4,0,0],[1,4,0,1]])


In [90]:
s = structure(seed, seed_next_possible)

s.generate(5)

initialized data: 
 [[0 0 0]
 [0 1 0]
 [0 2 0]
 [0 3 0]
 [0 4 0]]
step  1
data: 
 [[0 0 0]
 [0 1 0]
 [0 2 0]
 [0 3 0]
 [0 4 0]
 [1 4 0]
 [2 4 0]
 [3 4 0]
 [4 4 0]
 [5 4 0]]
step  2
data: 
 [[0 0 0]
 [0 1 0]
 [0 2 0]
 [0 3 0]
 [0 4 0]
 [1 4 0]
 [2 4 0]
 [3 4 0]
 [4 4 0]
 [5 4 0]
 [5 4 1]
 [5 4 2]
 [5 4 3]
 [5 4 4]
 [5 4 5]]
step  3
data: 
 [[0 0 0]
 [0 1 0]
 [0 2 0]
 [0 3 0]
 [0 4 0]
 [1 4 0]
 [2 4 0]
 [3 4 0]
 [4 4 0]
 [5 4 0]
 [5 4 1]
 [5 4 2]
 [5 4 3]
 [5 4 4]
 [5 4 5]
 [5 5 5]
 [5 6 5]
 [5 7 5]
 [5 8 5]
 [5 9 5]]
step  4
data: 
 [[ 0  0  0]
 [ 0  1  0]
 [ 0  2  0]
 [ 0  3  0]
 [ 0  4  0]
 [ 1  4  0]
 [ 2  4  0]
 [ 3  4  0]
 [ 4  4  0]
 [ 5  4  0]
 [ 5  4  1]
 [ 5  4  2]
 [ 5  4  3]
 [ 5  4  4]
 [ 5  4  5]
 [ 5  5  5]
 [ 5  6  5]
 [ 5  7  5]
 [ 5  8  5]
 [ 5  9  5]
 [ 5  9  6]
 [ 5  9  7]
 [ 5  9  8]
 [ 5  9  9]
 [ 5  9 10]]
step  5
data: 
 [[ 0  0  0]
 [ 0  1  0]
 [ 0  2  0]
 [ 0  3  0]
 [ 0  4  0]
 [ 1  4  0]
 [ 2  4  0]
 [ 3  4  0]
 [ 4  4  0]
 [ 5  4  0]
 [ 5  4  1]
 [ 5  4  2]
 

In [14]:
class rect:
    def __init__(self, startPos, scale): 
        self.start_x = startPos[0];
        self.start_y = startPos[1];
        self.start_z = startPos[2];
        
        self.scale_x = scale[0];
        self.scale_y = scale[1];
        self.scale_z = scale[2];
    
    def info(self):
        print("start_x:",self.start_x,"start_y:",self.start_y,"start_z:",self.start_z)
        print("scale_x:",self.scale_x,"scale_y:",self.scale_y,"scale_z:",self.scale_z)

    

In [6]:
a = rect(np.array([0,0,0]), np.array([1,1,1]))
next_possible = np.array([0,1,0])

In [20]:
b = np.array([(0,0,0), (0,-1,0), (0,-2,0),(0,-3,0)])

In [29]:
def block_to_rect(buffer):
    start = buffer[0]
    end = buffer[-1]
    x_start = min(start[0],end[0])
    y_start = min(start[1],end[1])    
    z_start = min(start[2],end[2])
    
    x_scale = max(abs(start[0] - end[0]), 1)
    y_scale = max(abs(start[1] - end[1]), 1)
    z_scale = max(abs(start[2] - end[2]), 1)
    print(x_scale)
    
    startPos = np.array([x_start,y_start,z_start])
    scale = np.array([x_scale,y_scale,z_scale])
    
    tempt = rect(startPos, scale)
    return tempt

In [30]:
rect_b = block_to_rect(b)

1


In [31]:
rect_b.info()

start_x: 0 start_y: -3 start_z: 0
scale_x: 1 scale_y: 3 scale_z: 1


In [62]:
c = np.array([[0,0,0], [0,-1,0], [0,-2,0],[0,-3,0]])

In [ ]:
next_possibles = np.array([])

In [63]:
buffer = c[0]

In [64]:
for i in range(1,len(c)):
    buffer = np.vstack([buffer, c[i]])

In [65]:
buffer

array([[ 0,  0,  0],
       [ 0, -1,  0],
       [ 0, -2,  0],
       [ 0, -3,  0]])

In [67]:
seed = np.array([[0,0,0], [0,1,0],[0,2,0],[0,3,0], [0,4,0]])
seed_next_possible = np.array([[-1,4,0,0],[1,4,0,1],[0,4,-1,4], [0,4,1,5]])


In [68]:
def cost_func(self, pos):
    return pos[0] + pos[1] + pos[2] + random.random()

In [70]:
costs = np.array([])
for next_possible in seed_next_possible:
    costs = np.append(costs, cost_func(seed_next_possible))

TypeError: cost_func() missing 1 required positional argument: 'pos'